server:
  port: 8685


spring:
  datasource:
    url: jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #hikari:
      #maximumPoolSize: 80
  data:
    mongodb:
      #uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
      uri: mongodb-hx-gwasdepopro-001.ebi.ac.uk:27017,mongodb-hl-gwasdepopro-002.ebi.ac.uk:27017/admin?replicaSet=gwasdepoprors080

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 10


executor:
  thread-pool:
    count:

association:
  partition:
    size:

gwas-curation:
  #db: deposition-backend-sandbox
  db: gwasdepo

rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox


