server:
  port: 8685


spring:
  datasource:
    url: jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #hikari:
      #maximumPoolSize: 80
  data:
    mongodb:
      #uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
      uri: mongodb-hx-gwasdepopro-001.ebi.ac.uk:27017,mongodb-hl-gwasdepopro-002.ebi.ac.uk:27017/admin?replicaSet=gwasdepoprors080
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 10


logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type: ERROR

executor:
  thread-pool:
    count:

entity:
  partition:
    size:

gwas-curation:
  #db: deposition-backend-sandbox
  db: gwasdepo

rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox

#script: /hps/software/users/parkinso/spot/gwas/prod/sw/mapping-pipeline/run-bjobs-mapper.sh
script: /hps/software/users/parkinso/spot/gwas/prod/sw/data-copy-service/run-slurm-copy-oracle-mongo.sh
slurm:
  logslocation: /hps/nobackup/parkinso/spot/gwas/logs/data-copy-service/logs/bsub
