server:
  port: 8685


spring:
  datasource:
    url: jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #hikari:
      #maximumPoolSize: 80
  data:
    mongodb:
      #uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
      uri: mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 10


logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type: ERROR

executor:
  thread-pool:
    count:

entity:
  partition:
    size:


#script: /hps/software/users/parkinso/spot/gwas/prod/sw/mapping-pipeline/run-bjobs-mapper.sh
script: /hps/software/users/parkinso/spot/gwas/prod/sw/data-copy-service/run-slurm-mapper.sh
slurm:
  logslocation: /hps/nobackup/parkinso/spot/gwas/logs/data-copy-service/logs/bsub
