server:
  port: 8084


spring:
  datasource:
    url: jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximumPoolSize: 80
  jpa:
    hibernate:
      ddl-auto: none


logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type: ERROR

executor:
  thread-pool:
    count:

association:
  partition:
    size: 


#script: /hps/software/users/parkinso/spot/gwas/prod/sw/mapping-pipeline/run-bjobs-mapper.sh
script: /hps/software/users/parkinso/spot/gwas/prod/sw/mapping-pipeline/run-slurm-mapper.sh


