stages:
  - build
  - test
  - deploy

image: alpine

build_gwas-mapping-service:
  stage: build
  script:
    - echo "This job builds something. gwas-mapping-service"

test_gwas-mapping-service:
  stage: test
  needs: [build_gwas-mapping-service]
  script:
    - echo "This job tests something. gwas-mapping-service"

deploy_gwas-mapping-service:
  stage: deploy
  needs: [test_gwas-mapping-service]
  script:
    - echo "This job deploys something. gwas-mapping-service"
