server:
  port: 8080

spring:
  datasource:
    url: ''
    username: ''
    password: ''
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximumPoolSize: 80
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans:true
