server:
  port: 8685


spring:
  rabbitmq:
    host: hh-rke-wp-webadmin-09-worker-1.caas.ebi.ac.uk
    port: 30672
    username:
    password:
  datasource:
    #url: jdbc:oracle:thin:@ora-spot-dev2-hl.ebi.ac.uk:1521/SPOTDV2
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ora-spot-pro-hl.ebi.ac.uk)(PORT=1531))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=SPOTPRO)))
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #hikari:
      #maximumPoolSize: 80
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 10


executor:
  thread-pool:
    count:

association:
  partition:
    size:

gwas-curation:
  #db: deposition-backend-sandbox
  db: gwasdepo

rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox
  publication:
    queue-name: publication-sandbox
    exchange-name: publication-exchange-sandbox
    routing-key: publication-route-sandbox

